### ISSUE TITLE
Explain build / steps to reproduce?

### ISSUE THREAD

**Issue by gregglind** [likr/emlapack#1]
You have done a pretty awesome thing here.  Understanding the emscripten piece is hard, and I would love to hear more in the README.

**Comment by rreusser** [comment]
Submitted a PR. Haven't used emscripten before so thought for sure it would fail, but seemed to work fine!

**Comment by mikechau** [comment]
Hi @likr any interest in a docker build? We've forked the project to make it a little bit easier to do custom builds (ie, set everything up in docker then run a build which outputs everything to the project root). Happy to do a PR if you are interested.

**Comment by likr** [comment]
@mikechau, thank you for your nice work! I'll merge it.

**Comment by likr** [comment]
Tentatively, closed this issue.
